@echo off
cd /d "%~dp0"
echo 🔹 Активируем виртуальное окружение...
call env\Scripts\activate.bat
echo 🔹 Запускаем Python-скрипт...
python format_tag_in_collection.py
echo ✅ Готово! Нажмите любую клавишу для выхода...
pause
